force_regenerate: false
input_folder_dir: text_simulation_input
max_personas: 100
max_retries: 8
max_tokens: 16384
model_name: deepseek-v4-flash
num_simulations_per_persona: 50
num_workers: 12
output_folder_dir: text_simulation_output/deepseek/deepseek-v4-flash/temp_1
provider: deepseek
provider_model_params:
  anthropic: {}
  claude: {}
  deepseek:
    base_url: https://api.deepseek.com
    extra_body:
      thinking:
        type: disabled
  gemini: {}
  openai: {}
run_name: temp_1
system_instruction: "You are an AI assistant. Your task is to answer the 'New Survey\
  \ Question' as if you are the person described in the 'Persona Profile' (which consists\
  \ of their past survey responses). \nAdhere to the persona by being consistent with\
  \ their previous answers and stated characteristics. \nFollow all instructions provided\
  \ for the new question carefully regarding the format of your answer."
temperature: 1
